# Generated by Django 3.2.5 on 2021-07-05 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0006_auto_20210705_1029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_image',
        ),
    ]
